### ISSUE TITLE
-D fdb in 3.2.0 rc1

### ISSUE THREAD

**Issue by MSGhero** [HaxeFoundation/haxe#4021]
Doesn't work, says "unknown switch -Dfdb" and it wasn't documented if it was removed. Works fine in a fresh 3.1.3 install.

`lime test "project.xml" flash -debug -Dfdb`

Unrelated, or-equals `||=` doesn't work? I get compile errors using it, and I just assumed it would work since it's a valid operator in flash.

**Comment by nadako** [comment]
Haxe define syntax is `-D fdb` (note the space)

**Comment by Simn** [comment]
Actually that's an issue with haxelib. Looks like I didn't properly sync the repositories again after Juraj removed the unknown switch error. :(

Fortunately we haven't announced the release yet, so I'll just go ahead and overwrite the binaries.

**Comment by T1mL3arn** [comment]
After 3.2.0 rc1 installation, FlashDevelop haven't starts the debug session either directly ( from "Test Project" button) or remotely (Debug -> Start remote session). On some of old dev-build (6412bec) it works.

**Comment by Simn** [comment]
That's something you might have to report to FD first to figure out what exactly the problem is.

**Comment by T1mL3arn** [comment]
I just saw this issue about -D fdb and made post here. As far as I know, fdb flag enables interactive debugging for IDE. And after installing new haxe-rc debugger doesn't working.

**Comment by Simn** [comment]
I have updated the release binaries so this should be fixed now.

**Comment by MSGhero** [comment]
I also got @T1mL3arn's issue in 3.2.0, and in 3.2.01 (from 10 mins ago), my original issue is back.
