### ISSUE TITLE
CPP generation error (2)

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe#4331]
Another error in CPP generation with Evoland2 code.

This time it's a small function:

```
	public function restart(state, ?andSave, ?now) {
		function run() {
			dispose();
			inst = new Game(state, engine);
			if( andSave ) doSave();
		}
		if( now )
			run();
		else
			haxe.Timer.delay(function() {
				if( inst != this ) return;
				run();
			},1);
	}
```

And I get:

```
./src/Game.cpp(2691) : error C2365: 'Game_obj::restart::_Function_2_1::run'ÿ: red‚finitionÿ; la pr‚c‚dente d‚finition ‚tait 'donn‚es membres'

        ./src/Game.cpp(2689)ÿ: voir la d‚claration de 'Game_obj::restart::_Function_2_1::run'
```

Renaming `run` to `run_` fixed it so it seems related to some conflict with cpp internals (I don't have a run var or method in this class).

**Comment by ncannasse** [comment]
PS : that's all for now, it successfully compiles a 54MB exe :')

**Comment by Simn** [comment]
We could dig out https://github.com/HaxeFoundation/haxe/pull/3085 again, that should help quite a bit.

**Comment by Simn** [comment]
There's a good chance this has been resolved by the cppast changes.

**Comment by hughsando** [comment]
This one was still a problem - name of local variable  "run" in a closure.
```
    static function getRun() {
        function run() { }
        return function() run();
    }
```
Should be fixed by https://github.com/HaxeFoundation/haxe/commit/376168cddd11c69550ba4be3cc507466e086d186
