### ISSUE TITLE
java: null pointer on a switch matching a null

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/haxe#4481]
This snipet outputs "ok" in other targets (tested js, php, cs and cpp), but fails on java target with a NullPointer exception. Because it calls .hashCode without checking nullability.

Checked that it fails with 3.2.0 and development branch.

```haxe
class Test {
        static public function main() {
                switch (null) {
                        case "a": trace("a");
                        default: trace("ok");
                }
        }
}
```

```
Exception in thread "main" java.lang.NullPointerException
    at haxe.root.Test.main(Unknown Source)
    at haxe.root.Test.main(Unknown Source)
```

**Comment by Simn** [comment]
This is not specified to work. Switching on `null` only works if you actually have a `case null`, otherwise the result is unspecified.

**Comment by waneck** [comment]
I don't know. I think I'd rather fix this to make it like all the other
targets

**Comment by Simn** [comment]
Do you mean for String in particular or for all null switches?

**Comment by waneck** [comment]
I mean for String in particular! It shouldn't be a hard fix also

**Comment by Simn** [comment]
If your targets are the only ones that fail here I don't mind it it's fixed. I thought this issue was about null-matching in general.

**Comment by kevinresol** [comment]
```haxe
package;

class Main {
	static function main() {
		var s:String = null;
		
		switch s {
			case 'foo': trace('foo');
			default: trace('default');
		}
		
	}
}
```

The reason is that java string-swtiching is actually switching on`theString.hashCode()`. So a null input will cause a null pointer.

**Comment by RealyUniqueName** [comment]
I've fixed for Java, but had to disable the test for JVM for now. It has the same issue.

**Comment by Simn** [comment]
I still don't really understand why we're suddenly specifying this... But I also don't want to be the only target where this fails, so whatever.

**Comment by kevinresol** [comment]
This still fails on python

```haxe
class Main {
  static function main() {
    switch foo() {
      case "a": trace("a");
      case "bc": trace("bc");
      default: trace("ok");
    }
  }
  static function foo():String return null;
}
```

**Comment by Simn** [comment]
On Java it also still fails with `case "":`. The reason is that it has a hashCode of 0, so the case actually matches but then fails on the subsequent `equals` check.

**Comment by RealyUniqueName** [comment]
I took this implementation as a reference: https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#hashCode%28java.lang.Object%29
But apperantly that's not enough for strings.
We need to generate a jump to default case (if it exists) in case of `null`

**Comment by Simn** [comment]
> We need to generate a jump to default case (if it exists) in case of null

Indeed. I should actually be able to do that on JVM, but it's still quite annoying to fix. We also have to consider that there might not be a `default` case for block-level switches, in which case we have to jump to the end of the switch...

**Comment by Simn** [comment]
Fixed JVM.
