### ISSUE TITLE
[display] missing follow for signature completion

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#5141]
```haxe
typedef MyCallable = String->Void

class Main {
    static function main() {
        var f1:MyCallable = function(s) {}
        f1(| // returns MyCallable :(
    }
}
```

**Comment by Simn** [comment]
I'm not sure that's bad. The typedef could have documentation that the followed type does not have.

Ideally we would show them both, but that raises protocol questions.

**Comment by nadako** [comment]
But it currently doesn't show any documentation, just `s_type`. It makes sense to follow it IMO. Since we can't get signature help from a typedef name at all.

As for the protocol, yeah, it's a good idea to check for documentation in a typedef when getting signature, I'll consider this for json output!

**Comment by Simn** [comment]
I'm assigning it to you because this should be solved as part of the JSON protocol.

**Comment by nadako** [comment]
I still don't understand how returning typedef name instead of the actual function type makes sense for the SIGNATURE help. Also, how would JSON protocol handle this differently?

**Comment by Simn** [comment]
I was thinking that it could show both the typedef and the type it resolves to, and then the IDE can decide what to show exactly. Maybe you're right and it doesn't make much sense for signature display though.
