### ISSUE TITLE
[lua] File.getBytes() throws exception with existing file

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe#5235]
I'm trying a bunch of my projects with the new lua target lately, and this came up (reduced example):

Code:
```haxe
import haxe.io.Path;
import sys.FileSystem;
import sys.io.File;


class ReadBytes {

    static var inputFileName:String = "ReadBytes.hx";
	
    static public function main() {
 
        var currentDir = Sys.getCwd();
        trace('cwd: $currentDir');
        
        var inputFilePath = Path.join([currentDir, inputFileName]);
        trace('inputFile: ${inputFilePath.toString()}');

        var exists = FileSystem.exists(inputFilePath.toString());
        trace('exists: $exists');
        
        var bytes = File.getBytes(inputFileName);
        trace(bytes.length);
    }    
}
```

Error: `lua: readBytes.lua:1070: readBytes.lua:1598: bad argument #1 to 'byte' (string expected, got nil)`.

**Comment by azrafe7** [comment]
Seems that the problem is that EOF is not recognized correctly, as `sys.io.FileInput.readByte()` prints all the chars fine until the last one (unfortunately haven't yet been able to find a solution, but maybe this could help).

**Comment by azrafe7** [comment]
Took a closer look and think I've found the origin of the problem. It's actually a two-part issue:

1. File.read/write is forgetting to add the binary 'b' flag (https://github.com/HaxeFoundation/haxe/blob/97f588212f627430a4be098816b3f449561343a0/std/lua/_std/sys/io/File.hx#L53-L59)
2. handling of EOF in FileInput.readByte (and consequently readAll/readBytes) is missing

Fixing both seems to also solve #5238.

For n. 2 [this code](https://gist.github.com/azrafe7/98c8c7437ec2fb4f78aaafa7d3741eb9) is working  for me so far.

**Comment by jdonaldson** [comment]
Thanks for these.  The sys/file support in Lua is pretty weak.  I don't have it passing the haxe sys test suite yet.

I've committed some fixes here that should address these problems.  Let me know if those work for you.

**Comment by azrafe7** [comment]
There's still a problem with this issue and the latest commit. Calling getContent() from getBytes() opens the file in text mode, so I'm getting an incorrect number of bytes back (I'm on win).

**Comment by azrafe7** [comment]
Taking a look at the cs implementation it seems that _something like this_ could work for lua as well:

`FileInput.hx`
```haxe
	override public function readBytes(s:Bytes, pos:Int, len:Int):Int
	{
		if( pos < 0 || len < 0 || pos + len > s.length )
			throw haxe.io.Error.OutsideBounds;
		
		var str = f.read(len);
		if (str == null) 
			str = ""; // assume eof
		
		var bytes = Bytes.ofString(str);
		s.blit(0, bytes, pos, bytes.length);
		if (str == "") 
			throw new haxe.io.Eof();
			
		return bytes.length;
	}
```

`File.hx`
```haxe
	public static function getBytes( path : String ) : haxe.io.Bytes {
		var f = Io.open(path, "rb");
		var s = f.read(All);
		f.close();
		return haxe.io.Bytes.ofString(s);
	}
```

What you think?

**Comment by jdonaldson** [comment]
Yep, we're on the same page here. I think the best idea is to fix the default haxe.io.Input implementation, and then benchmark a few methods and see what's most efficient for Lua.  It shouldn't take long to get to the bottom of this.

**Comment by ncannasse** [comment]
You want to avoid using Bytes.ofString here, because when reading big files it will allocate twice the data.

**Comment by ncannasse** [comment]
And yes default readBytes should be fixed to handle Eof , although it should absolutely be overridden if you expect decent performances.

**Comment by jdonaldson** [comment]
I added a fix for the lua specific FileInput problem.  I'll update things if we decide to change haxe.io.Input.

**Comment by azrafe7** [comment]
@jdonaldson can you please also push a fix for getBytes(), which currently uses text mode instead of binary?

**Comment by jdonaldson** [comment]
Yep, just pushed a fix for that.  I can't test though, since my mac doesn't need a binary flag.  Can you take a look?

**Comment by azrafe7** [comment]
Just did (on win) and it's fine, thanks!

**Comment by jdonaldson** [comment]
cool!  Glad to drop these.  Tests are pending, since I think the sys unit tests already cover this.
