### ISSUE TITLE
JsonParser.hx produces bad Actionscript Bytecode (incompatible with iOS AOT conversion)

### ISSUE THREAD

**Issue by TomByrne** [HaxeFoundation/haxe#5390]
There is an issue with the ABC that is produced by the JsonParser class.
It can't be successfully processed by the AOT conversion when creating an Adobe AIR build for iOS.
The reported error:

```
Bitcast requires types of same width
  %"atom2int_cast!18" = bitcast i64 %"atom2int_cast!" to i32
Bitcast requires types of same width
  %"atom2int212_cast!225" = bitcast i64 %"atom2int212_cast!" to i32
LLVM ERROR: Broken function found, compilation aborted!
Stack dump:
0.      Running pass 'Function Pass Manager' on module 'AOTBuildOutput-0000000000_0'.
1.      Running pass 'Module Verifier' on function '@"AOTBuildOutput-0000000000_0:610:haxe.format::JsonParser/parseRec"'
```

I have tried to distill the issue down to a few lines, this is how far I got:

```
    var arr = [];
    var comma : Null<Bool> = null;
    var c = "p";
    while( true ) {
        switch( c ) {
            case ']':
                if ( arr == [] ) arr = [];
            default:
                comma = true;
        }
    }
```

JsonParser gets included in a default OpenFL project, meaning that OpenFL SWFs cannot be used on iOS without workarounds. I understand that most people don't use OpenFL in this way.

If anyone is looking for a temporary workaround:

```
function parseRec() : Dynamic {
    #if flash
        return flash.utils.JSON.parse(str);
    #else
        < Existing Function Code >
    #end
}
```

**Comment by nadako** [comment]
This looks a lot like #4992. Could you try disabling haxe's json (in favor of native one) with the solution presented here: https://github.com/HaxeFoundation/haxe/issues/4992#issuecomment-203473306 ?

**Comment by TomByrne** [comment]
The reason I think that a issue could be done in Haxe (instead of in the Adobe AOT system) is that when I generate AS3 from Haxe, then compile that to a SWF using Adobe's tools, the AOT conversion works.
It only has a problem if I directly generate a SWF from Haxe.

**Comment by TomByrne** [comment]
Also, I haven't come across the "haxeJSON" flag before, but we are not using it in our projects.
I'm not sure whether the behaviour around this flag has changed because I can't really find any documentation about it.

**Comment by ncannasse** [comment]
Here's the same bytecode with analyzer disable:
```
function main : 
	   0 array 0
	   1 cast Array
	   2 setreg 1
	   3 null
	   4 asany
	   5 asany
	   6 setreg 2
	   7 string "p"
	   8 cast String
	   9 setreg 3
	  10 jump 15
	  11 label
	  12 reg 3
	  13 string "]"
	  14 jump-neq 8
	  15 reg 1
	  16 array 0
	  17 jump-neq 4
	  18 array 0
	  19 cast Array
	  20 setreg 1
	  21 jump 4
	  22 true
	  23 asany
	  24 setreg 2
	  25 true
	  26 jump-if -15
	  27 retvoid
```

**Comment by TomByrne** [comment]
Sorry, I think that code snippet was not quite right (i.e. was not producing the AOT error).
it should be:
```
var comma : Null<Bool> = null;
var c = "p";
while( true ) {
	switch( c ) {
		case ']'.code:
			if( comma == false ) return;
		default:
			if( comma ) return;
			comma = true;
	}
}
```
I'll be able to do a test with 3.3 later in the week, but this is with 3.2.1.
Here's the bytecode produced (as exported by RABCDA):
```
     pushnull
     astype              QName(PackageNamespace("", "#0"), "String")
     setlocal3

     pushnull
     coerce_a
     coerce_a
     setlocal1

     pushstring          "p"
     coerce              QName(PackageNamespace("", "#0"), "String")
     setlocal2

     jump                L29

L11:
     label
     getlocal2
     coerce              QName(PackageNamespace("", "#0"), "String")
     setlocal3

     getlocal3
     pushbyte            93
     ifne                L23

     getlocal1
     pushfalse
     ifne                L22

     returnvoid

L22:
     jump                L29

L23:
     getlocal1
     iffalse             L26

     returnvoid

L26:
     pushtrue
     coerce_a
     setlocal1

L29:
     pushtrue
     iftrue              L11

     returnvoid
```

**Comment by ncannasse** [comment]
Was this fixed with 3.3 or 3.4 RC ?

**Comment by TomByrne** [comment]
With 3.3 & 3.4rc1 I'm getting a compilation error:
`Int should be String`
from this line:
`case ']'.code:`

When I try to recompile JsonParser with 3.3 & 3.4 for SWF/iOS I still get the original error.
I'll attempt to narrow down the code again.

**Comment by TomByrne** [comment]
Here's a new example that fails AOT conversion in Haxe 3.4rc1

```
class MainMobile
{
	public function new() 
	{
		var comma : Null<Bool> = null;
		while( true ) {
			var c = "-".charCodeAt(0);
			switch( c ) {
				case ']'.code:
					if( comma == false ) throw "- ";
				default:
					if( comma ) throw "- ";
					comma = true;
			}
		}
	}
}
```

**Comment by Simn** [comment]
Moving towards Haxe 4, we will no longer look into fixing old Flash/SWF issues. We are still going to keep the generator up to date with all new Haxe features, but we don't have the resources to work on flash-specific bugs. Pull requests to fix them are still going to be reviewed and possibly accepted.
