### ISSUE TITLE
runtime error with lua and -dce no

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe#5807]
a simple hello world fails in lua at runtime with `-dce` no enabled: 
```
std/lua/Boot.hx:311: characters 31-34 : __lua_table__ only accepts array or anonymous object arguments
```

**Comment by jdonaldson** [comment]
this should be fixed.

**Comment by haik0925** [comment]
@jdonaldson 
It's not fixed...
var arr = [1, 2, 3, 4, 5];
var luaTable = lua.Table.create(arr);
Haxe still shows same error with the code above.

**Comment by jdonaldson** [comment]
You can only use this with an anonymous array reference, e.g:

lua.Table.create([1,2,3,4,5]);

The main issue is that Haxe arrays are 0-based, and lua tables are 1-based.  If you pass an anonymous array declaration, the compiler skips the array construction and stores the values directly into a table instance.  If you pass an array instance reference, then the array is already constructed, and the compiler can't optimize it.

It's a subtle gotcha, and I'll make a separate utility method for array references.

**Comment by jdonaldson** [comment]
I added some table helper methods : https://github.com/HaxeFoundation/haxe/commit/9360857555b99386f2fa61c2828ae741f765877c
