### ISSUE TITLE
$hxEnums is still not defined

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#7832]
```haxe
interface I1 {}

class Main {
	static public function main() {
		trace(Std.is(new Main(), I1));
	}

	function new() {}
}
```

```
ReferenceError: $hxEnums is not defined
    at Function.js_Boot.__instanceof (C:\GitHub\HaxeRepro\export\run.js:103:3)
```

**Comment by nadako** [comment]
All these features checks in genjs are so messy. I think we should have some `js.Internal` class with magic compiler-provided functions (similar to `js.Syntax`) and use it from all the things in `Type`/`Std`/`Boot` that need internal stuff like `$hxEnums`. Then we could rely on simple single feature checks.

**Comment by nadako** [comment]
But for now I'll put some band-aid of course.

**Comment by nadako** [comment]
Fixed by 5f18a08f57b805dd2bf8c1f5b263f80614ed157e

**Comment by Jarrio** [comment]
I still receive this error message, I have isolated the code down to a forwarded abstract that I'm using on the latest development build (Haxe Compiler 4.0.0-rc.1+030601e)

```haxe
typedef TStats = {
        var id:String;
	var type:String;
}

typedef TBar = {
	var a:Array<TStats>;
	var b:Array<TStats>;
}


@:forward abstract Foo(TBar) {
	function new(input) {
		this = input;
	}

	public function insert(data:Array<TStats>):Void {
		for (item in data) {
			if (item.type == "a") {
				this.a.push((item));
			}

			if (item.side == "b") {
				this.b.push((item));
			}
		}	
	}

	public function delete(data:Array<TStats>):Void {
		for (item in data) {
			var index = find(item);

			if (item.type == "a") {
				if (!this.a.remove(this.a[index])) {
					trace('Failed to remove: ', item);
				}
			}

			if (item.type == "b") {
				if (!this.b.remove(this.b[index])) {
					trace('Failed to remove: ', item);
				}
			}
		}
	}

	public function find(item:TStats):Int {
		var index = -1;
		var array = (item.type == "a") ? this.a : this.b;
		for (i in 0...array.length) {
			if (array[i].id == item.id ) {
				index = i;
				break;
			}
		}		
		return index;
	}
}
```

The key seems to be something to do with the `delete` function, if I keep `insert` and comment out `delete` the error goes away. `find()` does not seem to be causing any issues either.

I'm running the latest dev branch `Haxe Compiler 4.0.0-rc.1+030601e`

**Comment by nadako** [comment]
Thanks, I will investigate this!

**Comment by nadako** [comment]
@Jarrio is this a full example? Compiling this code (by adding an empty `main` and changing `side` to `type`) gives me only one `$hxEnums` usage in the generated code, guarded by `if (o.__enum__)` which will always be false, because there are no enums in the output, and if there were, `$hxEnums` would be generated. Can you please provide a more reproducible example? :)

**Comment by Jarrio** [comment]
I will have to check this when I get back home, I was trying to narrow it down and did find it odd that the part of the code that was causing this error had no enum's in it. I did have a switch wrapping around it for execution
```haxe
switch (data.type) {
     case EnumAbstract.A: { //created using the new code "enum abstract EnumAbstract(String){}"
          data.delete(info);
     }
     case EnumAbstract.B: {
          data.insert(info);
     }
}
```
But commenting out the enums didn't make a difference, it was only until I commented out the delete function did the error go away so I figured that was the cause

**Comment by Jarrio** [comment]
I can't seem to reproduce the scenario as I had worked around that issue :( I'm unsure as to whether it was my project or the new output target

**Comment by Simn** [comment]
I have moved this to 4.1 because there is no reproducible example at the moment.

**Comment by Simn** [comment]
I'll go ahead and close this as there's no reproducible example still. Please reopen if you find something.
