### ISSUE TITLE
[display] hang when interacting with `@:hlNative` usages

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8110]
To reproduce:

- open `haxe\std\hl\_std\sys\net\Socket.hx`
- invoke a hover request on some specific `socket_` calls, for instance `socket_init();` in line 113
- `haxe.exe` is now in some infinite recursion and all further display requests hang

This seems to be triggered by a very recent "regression" / fix. Even in rc.2, this didn't trigger a hang (instead, I simply get a `Display file was not found in class path` error on any request in `Socket.hx`).

**Comment by ncannasse** [comment]
git bisect ? ;)

**Comment by RealyUniqueName** [comment]
This is probably fixed with recent fixes:

![hover](https://i.imgur.com/dZmPb7D.png)

@Gama11 please, check if you can reproduce it with the latest dev Haxe.

**Comment by Gama11** [comment]
Still reproduces for me with 97aa17087de7376ca39ebe556a9693ea4c85388d.

**Comment by Gama11** [comment]
With verbose mode, I'm endlessly getting this in the output:

```
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
 1, hl: parsed c:\users\jens\github\haxe\std\hl\_std\sys\net\socket.hx (not cached, is display file)
```

Seems very similar to https://github.com/HaxeFoundation/haxe/issues/7236.

**Comment by RealyUniqueName** [comment]
Can reproduce by hovering `sock_init` here: 
https://github.com/HaxeFoundation/haxe/blob/97aa17087de7376ca39ebe556a9693ea4c85388d/std/hl/_std/sys/net/Socket.hx#L112-L114

**Comment by RealyUniqueName** [comment]
The server recursively runs in this call stack:
```
 (haxe/_build/src/context/typecore.ml:261)
 (haxe/_build/src/typing/typeload.ml:755)
 (haxe/_build/src/context/typecore.ml:421)
 (haxe/_build/src/typing/typerDisplay.ml:51)
 (haxe/_build/src/typing/typerDisplay.ml:276)
 (haxe/_build/src/typing/typer.ml:1418)
 (haxe/_build/src/typing/typer.ml:2252)
 (haxe/_build/src/typing/typer.ml:1564)
 (haxe/_build/src/typing/typer.ml:1567)
 (haxe/_build/src/typing/typer.ml:2372)
 (haxe/_build/src/typing/typeloadFunction.ml:133)
 (Std:26)
 (haxe/_build/src/typing/typeloadFields.ml:1071)
 (haxe/_build/src/context/typecore.ml:275)
 (haxe/_build/src/typing/typeloadFields.ml:1455)
 (haxe/_build/src/context/typecore.ml:261)
```
Entered for the first time from here: 
` (haxe/_build/src/typing/finalization.ml:47)`

It looks like some delayed typing causes it.

**Comment by Gama11** [comment]
Hm... it seems this is now fixed for hover requests, but I can still trigger a hang if I invoke completion within that `__init__()` function with <kbd>Ctrl</kbd>+<kbd>Space</kbd> (in other places too).

![](https://i.imgur.com/DYI8RjA.png)

Not sure if it's the same hang.
