### ISSUE TITLE
Constrained monomorph and `<T:{}>` constraint

### ISSUE THREAD

**Issue by kLabz** [HaxeFoundation/haxe#9593]
This used to work (`<T:{}>` is just a hint that we want anon objects here) before constrained monomorph, but now results in error below:

```haxe
class Test {
  static function main() {
    foo(function(res) trace(res.error));
  }

  static function foo<T:{}>(cb:T->Void):Void {}
}
```

```
Test.hx:3: characters 31-36 : Unknown<0> : { } has no field error
```

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe/commit/1dd111b11563dd38fe1cfa950772c052379738c3

**Comment by kLabz** [comment]
This example is indeed fixed, but it was reduced too much and this still doesn't work:

```haxe
class Test {
  static function main() {
    foo(function(res) {
      trace(res.error);
      trace(res.file); // Unknown<0> : { error : Unknown<1> } has no field file
    });
  }

  static function foo<T:{}>(cb:T->Void):Void {}
}
```

(Note that it worked in a previous "the-rudy-files" branch state)
