### ISSUE TITLE
abstract class TODOs

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#9720]
* [x] check `abstract override`: This is fine and is also allowed by other languages.
* [ ] check constructors
* [x] add `isAbstract` flags to functions and classes in the display API
* [x] add `isAbstract` flags to functions and classes in the XML output for dox
* [x] add `isAbstract` flags to functions and classes in the macro API

**Comment by Simn** [comment]
Another open question is if `override` should be required to implement an abstract method of a parent class. I don't really have a strong opinion on that and can see arguments for both sides.

**Comment by RealyUniqueName** [comment]
There was a discussion on that matter in the evolution thread starting from [this message](https://github.com/HaxeFoundation/haxe-evolution/pull/69#issuecomment-570702936)

**Comment by RealyUniqueName** [comment]
> add isAbstract flags to functions and classes in the macro API

Isn't this solved by `AAbstract` accessor?

**Comment by Gama11** [comment]
> Isn't this solved by `AAbstract` accessor?

Still missing from `haxe.macor.Type.ClassType` and such as far as I can tell?

**Comment by RealyUniqueName** [comment]
Since nobody knows what does "check constructors" mean I consider this issue resolved.
